variables:
  catalog_name:
    description: Catalogo utilizado para criar os objetos
    default: ctakamiya_bundle
  
  full_email:
    description: "The current user's email"
    default: ${workspace.current_user.userName}
  
  my_user_name:
    description: "The current user's name (before @)"
    default: ${var.full_email.split("@")[0]}

  antenna_warehouse_id:
    description: "The ID of the SQL Warehouse utilized during the ETL process."
    # Change the ID 
    default: 239aa7f74824810e
